name: pro_spo18
description: ""
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">= 3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: 16.3.0
  get_it: 8.2.0
  injectable: 2.5.2
  flutter_bloc: 9.1.1
  equatable: 2.0.7
  flutter_dotenv: 6.0.0
  http: 1.5.0
  path_provider: 2.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: 8.2.0
  injectable_generator: 2.9.0
  build_runner: 2.9.0
  bloc_lint: 0.3.2

flutter:
  uses-material-design: true
  # fonts:
  #   - family: Outfit
  #     fonts:
  #       - asset: assets/fonts/outfit/Outfit-ExtraBold.ttf
  #         weight: 800
  #       - asset: assets/fonts/outfit/Outfit-Regular.ttf
  #         weight: 400
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
  #         weight: 400


  # assets:
    # - assets/icons/
    # - assets/images/
    # - assets/fonts/
    # - .env
